targets:
  $default:
    sources:
      - lib/**
      - web/**
      - "tool/**"
      - pubspec.yaml
      - lib/$lib$
      - $package$
    builders:
      drift_dev:
        # These options change how drift generates code
        options:
          databases:
            my_database: lib/database/database.dart
          sql:
            dialect: sqlite
            options:
              version: "3.38"
              modules: [fts5]